#+LaTeX_CLASS: elife-paper
#+LATEX_HEADER:\usepackage[utf8]{inputenc}
#+OPTIONS: tex:t
#+OPTIONS: toc:nil
#+OPTIONS: H:7 num:0
# +LaTeX_CLASS_OPTIONS: []
#+LATEX_HEADER:\sisetup{detect-all}
# https://submit.elifesciences.org/html/elife_author_instructions.html
#+AUTHOR:
#+TITLE: 

 #+BEGIN_LATEX
 \begin{figure}
 \begin{fullwidth}
 \centering\includegraphics[width=0.85\linewidth]{./figures/supplemental/sfigure1_multipanel.pdf}
 \caption*{\textbf{Figure 1 - Supplement 1. }\textbf{A} Pearson's correlation matrix with heirarchical clustering for whole-transcriptome normalized RNA-seq gene counts from epithelium isolated from the tissues indicated on the axes. \textbf{B} Pearson's correlation coefficient for the comparison of whole-transcriptome normalized RNA-seq gene counts between each of the sample types listed on the x-axis and adult small intestinal epithelium. \textit{P}-value indicates the results of an unpaired two-sided Student's \textit{t}-test. \textbf{C} Principle component analysis of whole-transcriptome RNA-seq normalized gene counts. Cumulative explained variance for PC1 and PC2 is indicated as a percentage on the x- and y-axes, respectively. \textbf{D} Density plot of the Log$_{2}$-transformed Fold change in gene expression in epithelium from transplanted HIOs over epithelium from HIOs cultured \textit{in vitro} plotted against the Log$_{2}$-transformed Fold change in gene expression in adult small intestinal epithelium over fetal small intestinal epithelium. The intensity of the blue color indicates the density of points in 2-dimensional space. SI, small intestine; tx, transplanted tissue; hPSC, human pluripotent stem cell; HIO, human intestinal organoid}
 \label{fig:fullwidth}
 \end{fullwidth}
 \end{figure}
 #+END_LATEX
